name: Auto Format

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22    

      - name: Install
        run: npm install prettier

      - name: Format
        run: npx prettier --write .

      - name: Install ESLint
        run: npm install eslint
      
      - name: Run ESLint
        run: npx eslint .

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "auto format [skip ci]" || echo "No changes"
          git push
